
package com.oracle.xmlns.primavera.p6.ws.udfvalue.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-04-24T11:49:39.361+05:30
 * Generated source version: 3.1.11
 */

@WebFault(name = "IntegrationFault", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1")
public class IntegrationFault extends Exception {
    
    private com.oracle.xmlns.primavera.p6.ws.integrationfaulttype.v1.IntegrationFaultType integrationFault;

    public IntegrationFault() {
        super();
    }
    
    public IntegrationFault(String message) {
        super(message);
    }
    
    public IntegrationFault(String message, Throwable cause) {
        super(message, cause);
    }

    public IntegrationFault(String message, com.oracle.xmlns.primavera.p6.ws.integrationfaulttype.v1.IntegrationFaultType integrationFault) {
        super(message);
        this.integrationFault = integrationFault;
    }

    public IntegrationFault(String message, com.oracle.xmlns.primavera.p6.ws.integrationfaulttype.v1.IntegrationFaultType integrationFault, Throwable cause) {
        super(message, cause);
        this.integrationFault = integrationFault;
    }

    public com.oracle.xmlns.primavera.p6.ws.integrationfaulttype.v1.IntegrationFaultType getFaultInfo() {
        return this.integrationFault;
    }
}
