
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.oracle.xmlns.primavera.p6.ws.udfvalue.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-04-24T11:49:39.366+05:30
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "UDFValueService",
                      portName = "UDFValuePort",
                      targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1",
                      wsdlLocation = "https://nyuhospitals-p6.oracleindustry.com/p6ws/services/UDFValueService?wsdl",
                      endpointInterface = "com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValuePortType")
                      
public class UDFValuePortImpl implements UDFValuePortType {

    private static final Logger LOG = Logger.getLogger(UDFValuePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValuePortType#getFieldLengthUDFValue(java.lang.String field)*
     */
    public int getFieldLengthUDFValue(java.lang.String field) throws IntegrationFault   { 
        LOG.info("Executing operation getFieldLengthUDFValue");
        System.out.println(field);
        try {
            int _return = 2094754690;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValuePortType#createUDFValues(java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValue> udfValue)*
     */
    public java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.CreateUDFValuesResponse.ObjectId> createUDFValues(java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValue> udfValue) throws IntegrationFault   { 
        LOG.info("Executing operation createUDFValues");
        System.out.println(udfValue);
        try {
            java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.CreateUDFValuesResponse.ObjectId> _return = new java.util.ArrayList<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.CreateUDFValuesResponse.ObjectId>();
            com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.CreateUDFValuesResponse.ObjectId _returnVal1 = new com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.CreateUDFValuesResponse.ObjectId();
            _returnVal1.setUDFTypeObjectId(-532739293);
            _returnVal1.setForeignObjectId(1596829163);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValuePortType#readUDFValues(java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValueFieldType> field, java.lang.String filter, java.lang.String orderBy)*
     */
    public java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValue> readUDFValues(java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValueFieldType> field, java.lang.String filter, java.lang.String orderBy) throws IntegrationFault   { 
        LOG.info("Executing operation readUDFValues");
        System.out.println(field);
        System.out.println(filter);
        System.out.println(orderBy);
        try {
            java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValue> _return = new java.util.ArrayList<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValue>();
            com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValue _returnVal1 = new com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValue();
            _returnVal1.setCodeValue("CodeValue-1884190060");
            javax.xml.bind.JAXBElement<java.lang.Integer> _returnVal1ConditionalIndicator = null;
            _returnVal1.setConditionalIndicator(_returnVal1ConditionalIndicator);
            javax.xml.bind.JAXBElement<java.lang.Double> _returnVal1Cost = null;
            _returnVal1.setCost(_returnVal1Cost);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1CreateDate = null;
            _returnVal1.setCreateDate(_returnVal1CreateDate);
            _returnVal1.setCreateUser("CreateUser-1224662672");
            _returnVal1.setDescription("Description316423078");
            javax.xml.bind.JAXBElement<java.lang.Double> _returnVal1Double = null;
            _returnVal1.setDouble(_returnVal1Double);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1FinishDate = null;
            _returnVal1.setFinishDate(_returnVal1FinishDate);
            _returnVal1.setForeignObjectId(Integer.valueOf(-1657325180));
            _returnVal1.setIndicator("Indicator-498791582");
            javax.xml.bind.JAXBElement<java.lang.Integer> _returnVal1Integer = null;
            _returnVal1.setInteger(_returnVal1Integer);
            javax.xml.bind.JAXBElement<java.lang.Boolean> _returnVal1IsBaseline = null;
            _returnVal1.setIsBaseline(_returnVal1IsBaseline);
            _returnVal1.setIsTemplate(Boolean.valueOf(true));
            javax.xml.bind.JAXBElement<java.lang.Boolean> _returnVal1IsUDFTypeCalculated = null;
            _returnVal1.setIsUDFTypeCalculated(_returnVal1IsUDFTypeCalculated);
            javax.xml.bind.JAXBElement<java.lang.Boolean> _returnVal1IsUDFTypeConditional = null;
            _returnVal1.setIsUDFTypeConditional(_returnVal1IsUDFTypeConditional);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1LastUpdateDate = null;
            _returnVal1.setLastUpdateDate(_returnVal1LastUpdateDate);
            _returnVal1.setLastUpdateUser("LastUpdateUser-50520143");
            javax.xml.bind.JAXBElement<java.lang.Integer> _returnVal1ProjectObjectId = null;
            _returnVal1.setProjectObjectId(_returnVal1ProjectObjectId);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1StartDate = null;
            _returnVal1.setStartDate(_returnVal1StartDate);
            _returnVal1.setText("Text-739347425");
            javax.xml.bind.JAXBElement<java.lang.Integer> _returnVal1UDFCodeObjectId = null;
            _returnVal1.setUDFCodeObjectId(_returnVal1UDFCodeObjectId);
            _returnVal1.setUDFTypeDataType("UDFTypeDataType1133538418");
            _returnVal1.setUDFTypeObjectId(Integer.valueOf(-2050043971));
            _returnVal1.setUDFTypeSubjectArea("UDFTypeSubjectArea-1960292691");
            _returnVal1.setUDFTypeTitle("UDFTypeTitle-1958476012");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValuePortType#deleteUDFValues(java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.DeleteUDFValues.ObjectId> objectId)*
     */
    public boolean deleteUDFValues(java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.DeleteUDFValues.ObjectId> objectId) throws IntegrationFault   { 
        LOG.info("Executing operation deleteUDFValues");
        System.out.println(objectId);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValuePortType#readCalculatedUDFValues(java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.CalculatedUDFValueFieldType> field, java.util.List<java.lang.Integer> udfTypeObjectId, java.util.List<java.lang.Integer> projectObjectId)*
     */
    public java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.ReadCalculatedUDFValuesResponse.CalculatedUDFValue> readCalculatedUDFValues(java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.CalculatedUDFValueFieldType> field, java.util.List<java.lang.Integer> udfTypeObjectId, java.util.List<java.lang.Integer> projectObjectId) throws IntegrationFault   { 
        LOG.info("Executing operation readCalculatedUDFValues");
        System.out.println(field);
        System.out.println(udfTypeObjectId);
        System.out.println(projectObjectId);
        try {
            java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.ReadCalculatedUDFValuesResponse.CalculatedUDFValue> _return = new java.util.ArrayList<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.ReadCalculatedUDFValuesResponse.CalculatedUDFValue>();
            com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.ReadCalculatedUDFValuesResponse.CalculatedUDFValue _returnVal1 = new com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.ReadCalculatedUDFValuesResponse.CalculatedUDFValue();
            javax.xml.bind.JAXBElement<java.lang.Integer> _returnVal1ConditionalIndicator = null;
            _returnVal1.setConditionalIndicator(_returnVal1ConditionalIndicator);
            javax.xml.bind.JAXBElement<java.lang.Double> _returnVal1Cost = null;
            _returnVal1.setCost(_returnVal1Cost);
            javax.xml.bind.JAXBElement<java.lang.Double> _returnVal1Double = null;
            _returnVal1.setDouble(_returnVal1Double);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1FinishDate = null;
            _returnVal1.setFinishDate(_returnVal1FinishDate);
            javax.xml.bind.JAXBElement<java.lang.Integer> _returnVal1Integer = null;
            _returnVal1.setInteger(_returnVal1Integer);
            _returnVal1.setProjectObjectId(-1653524017);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1StartDate = null;
            _returnVal1.setStartDate(_returnVal1StartDate);
            _returnVal1.setCalculatedUDFTypeDataType("CalculatedUDFTypeDataType-778316901");
            _returnVal1.setUDFTypeObjectId(1093921225);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValuePortType#updateUDFValues(java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValue> udfValue)*
     */
    public boolean updateUDFValues(java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValue> udfValue) throws IntegrationFault   { 
        LOG.info("Executing operation updateUDFValues");
        System.out.println(udfValue);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

}
