package com.oracle.xmlns.primavera.p6.ws.udfvalue.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-04-24T11:49:39.379+05:30
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", name = "UDFValuePortType")
@XmlSeeAlso({ObjectFactory.class, com.oracle.xmlns.primavera.p6.ws.integrationfaulttype.v1.ObjectFactory.class})
public interface UDFValuePortType {

    @WebMethod(action = "getFieldLengthUDFValue")
    @RequestWrapper(localName = "getFieldLengthUDFValue", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", className = "com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.GetFieldLengthUDFValue")
    @ResponseWrapper(localName = "getFieldLengthUDFValueResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", className = "com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.GetFieldLengthUDFValueResponse")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
    public int getFieldLengthUDFValue(
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
        java.lang.String field
    ) throws IntegrationFault;

    @WebMethod(operationName = "CreateUDFValues", action = "CreateUDFValues")
    @RequestWrapper(localName = "CreateUDFValues", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", className = "com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.CreateUDFValues")
    @ResponseWrapper(localName = "CreateUDFValuesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", className = "com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.CreateUDFValuesResponse")
    @WebResult(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
    public java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.CreateUDFValuesResponse.ObjectId> createUDFValues(
        @WebParam(name = "UDFValue", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
        java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValue> udfValue
    ) throws IntegrationFault;

    @WebMethod(operationName = "ReadUDFValues", action = "ReadUDFValues")
    @RequestWrapper(localName = "ReadUDFValues", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", className = "com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.ReadUDFValues")
    @ResponseWrapper(localName = "ReadUDFValuesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", className = "com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.ReadUDFValuesResponse")
    @WebResult(name = "UDFValue", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
    public java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValue> readUDFValues(
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
        java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValueFieldType> field,
        @WebParam(name = "Filter", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
        java.lang.String filter,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
        java.lang.String orderBy
    ) throws IntegrationFault;

    @WebMethod(operationName = "DeleteUDFValues", action = "DeleteUDFValues")
    @RequestWrapper(localName = "DeleteUDFValues", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", className = "com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.DeleteUDFValues")
    @ResponseWrapper(localName = "DeleteUDFValuesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", className = "com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.DeleteUDFValuesResponse")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
    public boolean deleteUDFValues(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
        java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.DeleteUDFValues.ObjectId> objectId
    ) throws IntegrationFault;

    @WebMethod(operationName = "ReadCalculatedUDFValues", action = "ReadCalculatedUDFValues")
    @RequestWrapper(localName = "ReadCalculatedUDFValues", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", className = "com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.ReadCalculatedUDFValues")
    @ResponseWrapper(localName = "ReadCalculatedUDFValuesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", className = "com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.ReadCalculatedUDFValuesResponse")
    @WebResult(name = "CalculatedUDFValue", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
    public java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.ReadCalculatedUDFValuesResponse.CalculatedUDFValue> readCalculatedUDFValues(
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
        java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.CalculatedUDFValueFieldType> field,
        @WebParam(name = "UDFTypeObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
        java.util.List<java.lang.Integer> udfTypeObjectId,
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
        java.util.List<java.lang.Integer> projectObjectId
    ) throws IntegrationFault;

    @WebMethod(operationName = "UpdateUDFValues", action = "UpdateUDFValues")
    @RequestWrapper(localName = "UpdateUDFValues", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", className = "com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UpdateUDFValues")
    @ResponseWrapper(localName = "UpdateUDFValuesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", className = "com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UpdateUDFValuesResponse")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
    public boolean updateUDFValues(
        @WebParam(name = "UDFValue", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1")
        java.util.List<com.oracle.xmlns.primavera.p6.ws.udfvalue.v1.UDFValue> udfValue
    ) throws IntegrationFault;
}
