package com.oracle.xmlns.primavera.p6.ws.udfvalue.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-04-24T11:49:39.386+05:30
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "UDFValueService", 
                  wsdlLocation = "https://nyuhospitals-p6.oracleindustry.com/p6ws/services/UDFValueService?wsdl",
                  targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1") 
public class UDFValueService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", "UDFValueService");
    public final static QName UDFValuePort = new QName("http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", "UDFValuePort");
    static {
        URL url = null;
        try {
            url = new URL("https://nyuhospitals-p6.oracleindustry.com/p6ws/services/UDFValueService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UDFValueService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://nyuhospitals-p6.oracleindustry.com/p6ws/services/UDFValueService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UDFValueService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UDFValueService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UDFValueService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UDFValueService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UDFValueService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UDFValueService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UDFValuePortType
     */
    @WebEndpoint(name = "UDFValuePort")
    public UDFValuePortType getUDFValuePort() {
        return super.getPort(UDFValuePort, UDFValuePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UDFValuePortType
     */
    @WebEndpoint(name = "UDFValuePort")
    public UDFValuePortType getUDFValuePort(WebServiceFeature... features) {
        return super.getPort(UDFValuePort, UDFValuePortType.class, features);
    }

}
