package com.oracle.xmlns.primavera.p6.ws.authentication.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-04-24T11:44:17.890+05:30
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", name = "AuthenticationServicePortType")
@XmlSeeAlso({ObjectFactory.class, com.oracle.xmlns.primavera.p6.ws.integrationfaulttype.v1.ObjectFactory.class})
public interface AuthenticationServicePortType {

    @WebMethod(operationName = "Logout", action = "urn:Logout")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "LogoutResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", partName = "result")
    public LogoutResponse logout(
        @WebParam(partName = "params", name = "Logout", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")
        java.lang.Object params
    );

    @WebMethod(operationName = "ReadSessionProperties", action = "urn:ReadSessionProperties")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ReadSessionPropertiesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", partName = "result")
    public ReadSessionPropertiesResponse readSessionProperties(
        @WebParam(partName = "params", name = "ReadSessionProperties", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")
        java.lang.Object params
    ) throws IntegrationFault;

    @WebMethod(operationName = "ReadDatabaseInstances", action = "urn:ReadDatabaseInstances")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ReadDatabaseInstancesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", partName = "result")
    public ReadDatabaseInstancesResponse readDatabaseInstances(
        @WebParam(partName = "params", name = "ReadDatabaseInstances", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")
        java.lang.Object params
    ) throws IntegrationFault;

    @WebMethod(operationName = "Login", action = "urn:Login")
    @RequestWrapper(localName = "Login", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", className = "com.oracle.xmlns.primavera.p6.ws.authentication.v1.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", className = "com.oracle.xmlns.primavera.p6.ws.authentication.v1.LoginResponse")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")
    public java.lang.Boolean login(
        @WebParam(name = "UserName", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")
        java.lang.String userName,
        @WebParam(name = "Password", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")
        java.lang.String password,
        @WebParam(name = "DatabaseInstanceId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")
        java.lang.Integer databaseInstanceId
    ) throws IntegrationFault;

    @WebMethod(operationName = "UpdateSessionProperties", action = "urn:UpdateSessionProperties")
    @RequestWrapper(localName = "UpdateSessionProperties", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", className = "com.oracle.xmlns.primavera.p6.ws.authentication.v1.UpdateSessionProperties")
    @ResponseWrapper(localName = "UpdateSessionPropertiesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", className = "com.oracle.xmlns.primavera.p6.ws.authentication.v1.UpdateSessionPropertiesResponse")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")
    public java.lang.Boolean updateSessionProperties(
        @WebParam(name = "IgnoreNullComplexFields", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")
        java.lang.Boolean ignoreNullComplexFields
    );
}
