package com.oracle.xmlns.primavera.p6.ws.authentication.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-04-24T11:44:17.895+05:30
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "AuthenticationService", 
                  wsdlLocation = "https://nyuhospitals-p6.oracleindustry.com/p6ws/services/AuthenticationService?wsdl",
                  targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1") 
public class AuthenticationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", "AuthenticationService");
    public final static QName AuthenticationServiceSOAP12PortHttp = new QName("http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", "AuthenticationServiceSOAP12port_http");
    static {
        URL url = null;
        try {
            url = new URL("https://nyuhospitals-p6.oracleindustry.com/p6ws/services/AuthenticationService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AuthenticationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://nyuhospitals-p6.oracleindustry.com/p6ws/services/AuthenticationService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuthenticationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthenticationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AuthenticationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AuthenticationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AuthenticationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AuthenticationServicePortType
     */
    @WebEndpoint(name = "AuthenticationServiceSOAP12port_http")
    public AuthenticationServicePortType getAuthenticationServiceSOAP12PortHttp() {
        return super.getPort(AuthenticationServiceSOAP12PortHttp, AuthenticationServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticationServicePortType
     */
    @WebEndpoint(name = "AuthenticationServiceSOAP12port_http")
    public AuthenticationServicePortType getAuthenticationServiceSOAP12PortHttp(WebServiceFeature... features) {
        return super.getPort(AuthenticationServiceSOAP12PortHttp, AuthenticationServicePortType.class, features);
    }

}
