
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.oracle.xmlns.primavera.p6.ws.authentication.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-04-24T11:44:17.873+05:30
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "AuthenticationService",
                      portName = "AuthenticationServiceSOAP12port_http",
                      targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1",
                      wsdlLocation = "https://nyuhospitals-p6.oracleindustry.com/p6ws/services/AuthenticationService?wsdl",
                      endpointInterface = "com.oracle.xmlns.primavera.p6.ws.authentication.v1.AuthenticationServicePortType")
                      
public class AuthenticationServiceSOAP12Port_HttpImpl implements AuthenticationServicePortType {

    private static final Logger LOG = Logger.getLogger(AuthenticationServiceSOAP12Port_HttpImpl.class.getName());

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.authentication.v1.AuthenticationServicePortType#logout(java.lang.Object params)*
     */
    public com.oracle.xmlns.primavera.p6.ws.authentication.v1.LogoutResponse logout(java.lang.Object params) { 
        LOG.info("Executing operation logout");
        System.out.println(params);
        try {
            com.oracle.xmlns.primavera.p6.ws.authentication.v1.LogoutResponse _return = new com.oracle.xmlns.primavera.p6.ws.authentication.v1.LogoutResponse();
            _return.setReturn(Boolean.valueOf(true));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.authentication.v1.AuthenticationServicePortType#readSessionProperties(java.lang.Object params)*
     */
    public com.oracle.xmlns.primavera.p6.ws.authentication.v1.ReadSessionPropertiesResponse readSessionProperties(java.lang.Object params) throws IntegrationFault   { 
        LOG.info("Executing operation readSessionProperties");
        System.out.println(params);
        try {
            com.oracle.xmlns.primavera.p6.ws.authentication.v1.ReadSessionPropertiesResponse _return = new com.oracle.xmlns.primavera.p6.ws.authentication.v1.ReadSessionPropertiesResponse();
            _return.setIsValid(false);
            _return.setUserObjectId(-1971020116);
            _return.setUserName("UserName-1996873365");
            _return.setDatabaseInstanceId(-502518741);
            _return.setDatabaseEncoding("DatabaseEncoding1744035482");
            _return.setDatabaseName("DatabaseName1870580336");
            com.oracle.xmlns.primavera.p6.ws.authentication.v1.DatabaseTypeType _returnDatabaseType = com.oracle.xmlns.primavera.p6.ws.authentication.v1.DatabaseTypeType.SQL_SERVER;
            _return.setDatabaseType(_returnDatabaseType);
            _return.setDatabaseUrl("DatabaseUrl617022436");
            _return.setIgnoreNullComplexFields(true);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.authentication.v1.AuthenticationServicePortType#readDatabaseInstances(java.lang.Object params)*
     */
    public com.oracle.xmlns.primavera.p6.ws.authentication.v1.ReadDatabaseInstancesResponse readDatabaseInstances(java.lang.Object params) throws IntegrationFault   { 
        LOG.info("Executing operation readDatabaseInstances");
        System.out.println(params);
        try {
            com.oracle.xmlns.primavera.p6.ws.authentication.v1.ReadDatabaseInstancesResponse _return = new com.oracle.xmlns.primavera.p6.ws.authentication.v1.ReadDatabaseInstancesResponse();
            java.util.List<com.oracle.xmlns.primavera.p6.ws.authentication.v1.ReadDatabaseInstancesResponse.DatabaseInstance> _returnDatabaseInstance = new java.util.ArrayList<com.oracle.xmlns.primavera.p6.ws.authentication.v1.ReadDatabaseInstancesResponse.DatabaseInstance>();
            com.oracle.xmlns.primavera.p6.ws.authentication.v1.ReadDatabaseInstancesResponse.DatabaseInstance _returnDatabaseInstanceVal1 = new com.oracle.xmlns.primavera.p6.ws.authentication.v1.ReadDatabaseInstancesResponse.DatabaseInstance();
            _returnDatabaseInstanceVal1.setDatabaseInstanceId(-1811225091);
            _returnDatabaseInstanceVal1.setDatabaseEncoding("DatabaseEncoding836629276");
            _returnDatabaseInstanceVal1.setDatabaseName("DatabaseName459489288");
            com.oracle.xmlns.primavera.p6.ws.authentication.v1.DatabaseTypeType _returnDatabaseInstanceVal1DatabaseType = com.oracle.xmlns.primavera.p6.ws.authentication.v1.DatabaseTypeType.SQL_SERVER;
            _returnDatabaseInstanceVal1.setDatabaseType(_returnDatabaseInstanceVal1DatabaseType);
            _returnDatabaseInstanceVal1.setDatabaseUrl("DatabaseUrl1512330172");
            _returnDatabaseInstance.add(_returnDatabaseInstanceVal1);
            _return.getDatabaseInstance().addAll(_returnDatabaseInstance);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.authentication.v1.AuthenticationServicePortType#login(java.lang.String userName, java.lang.String password, java.lang.Integer databaseInstanceId)*
     */
    public java.lang.Boolean login(java.lang.String userName, java.lang.String password, java.lang.Integer databaseInstanceId) throws IntegrationFault   { 
        LOG.info("Executing operation login");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(databaseInstanceId);
        try {
            java.lang.Boolean _return = Boolean.valueOf(false);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.authentication.v1.AuthenticationServicePortType#updateSessionProperties(java.lang.Boolean ignoreNullComplexFields)*
     */
    public java.lang.Boolean updateSessionProperties(java.lang.Boolean ignoreNullComplexFields) { 
        LOG.info("Executing operation updateSessionProperties");
        System.out.println(ignoreNullComplexFields);
        try {
            java.lang.Boolean _return = Boolean.valueOf(true);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
