
package com.oracle.xmlns.primavera.p6.ws.authentication.v1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-04-24T11:44:17.758+05:30
 * Generated source version: 3.1.11
 * 
 */
public final class AuthenticationServicePortType_AuthenticationServiceSOAP12PortHttp_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", "AuthenticationService");

    private AuthenticationServicePortType_AuthenticationServiceSOAP12PortHttp_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AuthenticationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AuthenticationService ss = new AuthenticationService(wsdlURL, SERVICE_NAME);
        AuthenticationServicePortType port = ss.getAuthenticationServiceSOAP12PortHttp();  
        
        {
        System.out.println("Invoking logout...");
        java.lang.Object _logout_params = null;
        com.oracle.xmlns.primavera.p6.ws.authentication.v1.LogoutResponse _logout__return = port.logout(_logout_params);
        System.out.println("logout.result=" + _logout__return);


        }
        {
        System.out.println("Invoking readSessionProperties...");
        java.lang.Object _readSessionProperties_params = null;
        try {
            com.oracle.xmlns.primavera.p6.ws.authentication.v1.ReadSessionPropertiesResponse _readSessionProperties__return = port.readSessionProperties(_readSessionProperties_params);
            System.out.println("readSessionProperties.result=" + _readSessionProperties__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking readDatabaseInstances...");
        java.lang.Object _readDatabaseInstances_params = null;
        try {
            com.oracle.xmlns.primavera.p6.ws.authentication.v1.ReadDatabaseInstancesResponse _readDatabaseInstances__return = port.readDatabaseInstances(_readDatabaseInstances_params);
            System.out.println("readDatabaseInstances.result=" + _readDatabaseInstances__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_userName = "_login_userName-258607489";
        java.lang.String _login_password = "_login_password-196460486";
        java.lang.Integer _login_databaseInstanceId = Integer.valueOf(-663214018);
        try {
            java.lang.Boolean _login__return = port.login(_login_userName, _login_password, _login_databaseInstanceId);
            System.out.println("login.result=" + _login__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateSessionProperties...");
        java.lang.Boolean _updateSessionProperties_ignoreNullComplexFields = Boolean.valueOf(false);
        java.lang.Boolean _updateSessionProperties__return = port.updateSessionProperties(_updateSessionProperties_ignoreNullComplexFields);
        System.out.println("updateSessionProperties.result=" + _updateSessionProperties__return);


        }

        System.exit(0);
    }

}
