
package com.oracle.xmlns.primavera.p6.ws.udftype.v1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-04-24T11:48:13.911+05:30
 * Generated source version: 3.1.11
 * 
 */
public final class UDFTypePortType_UDFTypePort_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1", "UDFTypeService");

    private UDFTypePortType_UDFTypePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UDFTypeService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UDFTypeService ss = new UDFTypeService(wsdlURL, SERVICE_NAME);
        UDFTypePortType port = ss.getUDFTypePort();  
        
        {
        System.out.println("Invoking getUDFFieldName...");
        int _getUDFFieldName_objectId = -591568710;
        try {
            java.lang.String _getUDFFieldName__return = port.getUDFFieldName(_getUDFFieldName_objectId);
            System.out.println("getUDFFieldName.result=" + _getUDFFieldName__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getFieldLengthUDFType...");
        java.lang.String _getFieldLengthUDFType_field = "_getFieldLengthUDFType_field-808879961";
        try {
            int _getFieldLengthUDFType__return = port.getFieldLengthUDFType(_getFieldLengthUDFType_field);
            System.out.println("getFieldLengthUDFType.result=" + _getFieldLengthUDFType__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteUDFTypes...");
        java.util.List<java.lang.Integer> _deleteUDFTypes_objectId = new java.util.ArrayList<java.lang.Integer>();
        java.lang.Integer _deleteUDFTypes_objectIdVal1 = Integer.valueOf(1025933366);
        _deleteUDFTypes_objectId.add(_deleteUDFTypes_objectIdVal1);
        try {
            boolean _deleteUDFTypes__return = port.deleteUDFTypes(_deleteUDFTypes_objectId);
            System.out.println("deleteUDFTypes.result=" + _deleteUDFTypes__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateUDFTypes...");
        java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType> _updateUDFTypes_udfType = new java.util.ArrayList<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType>();
        com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType _updateUDFTypes_udfTypeVal1 = new com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType();
        javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _updateUDFTypes_udfTypeVal1CreateDate = null;
        _updateUDFTypes_udfTypeVal1.setCreateDate(_updateUDFTypes_udfTypeVal1CreateDate);
        _updateUDFTypes_udfTypeVal1.setCreateUser("CreateUser174365723");
        _updateUDFTypes_udfTypeVal1.setDataType("DataType1240732253");
        javax.xml.bind.JAXBElement<java.lang.Boolean> _updateUDFTypes_udfTypeVal1IsCalculated = null;
        _updateUDFTypes_udfTypeVal1.setIsCalculated(_updateUDFTypes_udfTypeVal1IsCalculated);
        javax.xml.bind.JAXBElement<java.lang.Boolean> _updateUDFTypes_udfTypeVal1IsConditional = null;
        _updateUDFTypes_udfTypeVal1.setIsConditional(_updateUDFTypes_udfTypeVal1IsConditional);
        _updateUDFTypes_udfTypeVal1.setIsSecureCode(Boolean.valueOf(true));
        javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _updateUDFTypes_udfTypeVal1LastUpdateDate = null;
        _updateUDFTypes_udfTypeVal1.setLastUpdateDate(_updateUDFTypes_udfTypeVal1LastUpdateDate);
        _updateUDFTypes_udfTypeVal1.setLastUpdateUser("LastUpdateUser-803861828");
        _updateUDFTypes_udfTypeVal1.setObjectId(Integer.valueOf(493130007));
        _updateUDFTypes_udfTypeVal1.setSubjectArea("SubjectArea-1672425420");
        _updateUDFTypes_udfTypeVal1.setTitle("Title1018893200");
        _updateUDFTypes_udfType.add(_updateUDFTypes_udfTypeVal1);
        try {
            boolean _updateUDFTypes__return = port.updateUDFTypes(_updateUDFTypes_udfType);
            System.out.println("updateUDFTypes.result=" + _updateUDFTypes__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createUDFTypes...");
        java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType> _createUDFTypes_udfType = new java.util.ArrayList<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType>();
        com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType _createUDFTypes_udfTypeVal1 = new com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType();
        javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _createUDFTypes_udfTypeVal1CreateDate = null;
        _createUDFTypes_udfTypeVal1.setCreateDate(_createUDFTypes_udfTypeVal1CreateDate);
        _createUDFTypes_udfTypeVal1.setCreateUser("CreateUser-1739144543");
        _createUDFTypes_udfTypeVal1.setDataType("DataType-194073352");
        javax.xml.bind.JAXBElement<java.lang.Boolean> _createUDFTypes_udfTypeVal1IsCalculated = null;
        _createUDFTypes_udfTypeVal1.setIsCalculated(_createUDFTypes_udfTypeVal1IsCalculated);
        javax.xml.bind.JAXBElement<java.lang.Boolean> _createUDFTypes_udfTypeVal1IsConditional = null;
        _createUDFTypes_udfTypeVal1.setIsConditional(_createUDFTypes_udfTypeVal1IsConditional);
        _createUDFTypes_udfTypeVal1.setIsSecureCode(Boolean.valueOf(true));
        javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _createUDFTypes_udfTypeVal1LastUpdateDate = null;
        _createUDFTypes_udfTypeVal1.setLastUpdateDate(_createUDFTypes_udfTypeVal1LastUpdateDate);
        _createUDFTypes_udfTypeVal1.setLastUpdateUser("LastUpdateUser-1150708219");
        _createUDFTypes_udfTypeVal1.setObjectId(Integer.valueOf(152977853));
        _createUDFTypes_udfTypeVal1.setSubjectArea("SubjectArea-2039362901");
        _createUDFTypes_udfTypeVal1.setTitle("Title-175907605");
        _createUDFTypes_udfType.add(_createUDFTypes_udfTypeVal1);
        try {
            java.util.List<java.lang.Integer> _createUDFTypes__return = port.createUDFTypes(_createUDFTypes_udfType);
            System.out.println("createUDFTypes.result=" + _createUDFTypes__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking readUDFTypes...");
        java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFTypeFieldType> _readUDFTypes_field = new java.util.ArrayList<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFTypeFieldType>();
        com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFTypeFieldType _readUDFTypes_fieldVal1 = com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFTypeFieldType.IS_CONDITIONAL;
        _readUDFTypes_field.add(_readUDFTypes_fieldVal1);
        java.lang.String _readUDFTypes_filter = "_readUDFTypes_filter-690925858";
        java.lang.String _readUDFTypes_orderBy = "_readUDFTypes_orderBy-1475428059";
        try {
            java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType> _readUDFTypes__return = port.readUDFTypes(_readUDFTypes_field, _readUDFTypes_filter, _readUDFTypes_orderBy);
            System.out.println("readUDFTypes.result=" + _readUDFTypes__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
