
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.oracle.xmlns.primavera.p6.ws.udftype.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-04-24T11:48:14.014+05:30
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "UDFTypeService",
                      portName = "UDFTypePort",
                      targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1",
                      wsdlLocation = "https://nyuhospitals-p6.oracleindustry.com/p6ws/services/UDFTypeService?wsdl",
                      endpointInterface = "com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFTypePortType")
                      
public class UDFTypePortImpl implements UDFTypePortType {

    private static final Logger LOG = Logger.getLogger(UDFTypePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFTypePortType#getUDFFieldName(int objectId)*
     */
    public java.lang.String getUDFFieldName(int objectId) throws IntegrationFault   { 
        LOG.info("Executing operation getUDFFieldName");
        System.out.println(objectId);
        try {
            java.lang.String _return = "_return1045777461";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFTypePortType#getFieldLengthUDFType(java.lang.String field)*
     */
    public int getFieldLengthUDFType(java.lang.String field) throws IntegrationFault   { 
        LOG.info("Executing operation getFieldLengthUDFType");
        System.out.println(field);
        try {
            int _return = 497877846;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFTypePortType#deleteUDFTypes(java.util.List<java.lang.Integer> objectId)*
     */
    public boolean deleteUDFTypes(java.util.List<java.lang.Integer> objectId) throws IntegrationFault   { 
        LOG.info("Executing operation deleteUDFTypes");
        System.out.println(objectId);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFTypePortType#updateUDFTypes(java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType> udfType)*
     */
    public boolean updateUDFTypes(java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType> udfType) throws IntegrationFault   { 
        LOG.info("Executing operation updateUDFTypes");
        System.out.println(udfType);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFTypePortType#createUDFTypes(java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType> udfType)*
     */
    public java.util.List<java.lang.Integer> createUDFTypes(java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType> udfType) throws IntegrationFault   { 
        LOG.info("Executing operation createUDFTypes");
        System.out.println(udfType);
        try {
            java.util.List<java.lang.Integer> _return = new java.util.ArrayList<java.lang.Integer>();
            java.lang.Integer _returnVal1 = Integer.valueOf(966163534);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFTypePortType#readUDFTypes(java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFTypeFieldType> field, java.lang.String filter, java.lang.String orderBy)*
     */
    public java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType> readUDFTypes(java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFTypeFieldType> field, java.lang.String filter, java.lang.String orderBy) throws IntegrationFault   { 
        LOG.info("Executing operation readUDFTypes");
        System.out.println(field);
        System.out.println(filter);
        System.out.println(orderBy);
        try {
            java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType> _return = new java.util.ArrayList<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType>();
            com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType _returnVal1 = new com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType();
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1CreateDate = null;
            _returnVal1.setCreateDate(_returnVal1CreateDate);
            _returnVal1.setCreateUser("CreateUser1001301321");
            _returnVal1.setDataType("DataType-1898704401");
            javax.xml.bind.JAXBElement<java.lang.Boolean> _returnVal1IsCalculated = null;
            _returnVal1.setIsCalculated(_returnVal1IsCalculated);
            javax.xml.bind.JAXBElement<java.lang.Boolean> _returnVal1IsConditional = null;
            _returnVal1.setIsConditional(_returnVal1IsConditional);
            _returnVal1.setIsSecureCode(Boolean.valueOf(true));
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1LastUpdateDate = null;
            _returnVal1.setLastUpdateDate(_returnVal1LastUpdateDate);
            _returnVal1.setLastUpdateUser("LastUpdateUser-605422958");
            _returnVal1.setObjectId(Integer.valueOf(844511531));
            _returnVal1.setSubjectArea("SubjectArea-766972378");
            _returnVal1.setTitle("Title-235171945");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

}
