package com.oracle.xmlns.primavera.p6.ws.udftype.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-04-24T11:48:14.027+05:30
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1", name = "UDFTypePortType")
@XmlSeeAlso({com.oracle.xmlns.primavera.p6.ws.integrationfaulttype.v1.ObjectFactory.class, ObjectFactory.class})
public interface UDFTypePortType {

    @WebMethod(operationName = "GetUDFFieldName", action = "GetUDFFieldName")
    @RequestWrapper(localName = "GetUDFFieldName", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1", className = "com.oracle.xmlns.primavera.p6.ws.udftype.v1.GetUDFFieldName")
    @ResponseWrapper(localName = "GetUDFFieldNameResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1", className = "com.oracle.xmlns.primavera.p6.ws.udftype.v1.GetUDFFieldNameResponse")
    @WebResult(name = "UDFFieldName", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1")
    public java.lang.String getUDFFieldName(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1")
        int objectId
    ) throws IntegrationFault;

    @WebMethod(action = "getFieldLengthUDFType")
    @RequestWrapper(localName = "getFieldLengthUDFType", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1", className = "com.oracle.xmlns.primavera.p6.ws.udftype.v1.GetFieldLengthUDFType")
    @ResponseWrapper(localName = "getFieldLengthUDFTypeResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1", className = "com.oracle.xmlns.primavera.p6.ws.udftype.v1.GetFieldLengthUDFTypeResponse")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1")
    public int getFieldLengthUDFType(
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1")
        java.lang.String field
    ) throws IntegrationFault;

    @WebMethod(operationName = "DeleteUDFTypes", action = "DeleteUDFTypes")
    @RequestWrapper(localName = "DeleteUDFTypes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1", className = "com.oracle.xmlns.primavera.p6.ws.udftype.v1.DeleteUDFTypes")
    @ResponseWrapper(localName = "DeleteUDFTypesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1", className = "com.oracle.xmlns.primavera.p6.ws.udftype.v1.DeleteUDFTypesResponse")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1")
    public boolean deleteUDFTypes(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1")
        java.util.List<java.lang.Integer> objectId
    ) throws IntegrationFault;

    @WebMethod(operationName = "UpdateUDFTypes", action = "UpdateUDFTypes")
    @RequestWrapper(localName = "UpdateUDFTypes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1", className = "com.oracle.xmlns.primavera.p6.ws.udftype.v1.UpdateUDFTypes")
    @ResponseWrapper(localName = "UpdateUDFTypesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1", className = "com.oracle.xmlns.primavera.p6.ws.udftype.v1.UpdateUDFTypesResponse")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1")
    public boolean updateUDFTypes(
        @WebParam(name = "UDFType", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1")
        java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType> udfType
    ) throws IntegrationFault;

    @WebMethod(operationName = "CreateUDFTypes", action = "CreateUDFTypes")
    @RequestWrapper(localName = "CreateUDFTypes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1", className = "com.oracle.xmlns.primavera.p6.ws.udftype.v1.CreateUDFTypes")
    @ResponseWrapper(localName = "CreateUDFTypesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1", className = "com.oracle.xmlns.primavera.p6.ws.udftype.v1.CreateUDFTypesResponse")
    @WebResult(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1")
    public java.util.List<java.lang.Integer> createUDFTypes(
        @WebParam(name = "UDFType", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1")
        java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType> udfType
    ) throws IntegrationFault;

    @WebMethod(operationName = "ReadUDFTypes", action = "ReadUDFTypes")
    @RequestWrapper(localName = "ReadUDFTypes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1", className = "com.oracle.xmlns.primavera.p6.ws.udftype.v1.ReadUDFTypes")
    @ResponseWrapper(localName = "ReadUDFTypesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1", className = "com.oracle.xmlns.primavera.p6.ws.udftype.v1.ReadUDFTypesResponse")
    @WebResult(name = "UDFType", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1")
    public java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFType> readUDFTypes(
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1")
        java.util.List<com.oracle.xmlns.primavera.p6.ws.udftype.v1.UDFTypeFieldType> field,
        @WebParam(name = "Filter", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1")
        java.lang.String filter,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFType/V1")
        java.lang.String orderBy
    ) throws IntegrationFault;
}
